Bluesky Vector Scan Conversion
NSLS-II-NYX/nyxtools pull request #20
Opened 2022-04-08 18:04 UTC by mskinner5278

2022-04-12 12:57 UTC, JunAishima requested changes
I don't think the flyer should be protocol-dependent (at least not between standard and vector). can you think of a way that this dependency can be removed so that it can be used for both types of experiments?

2022-04-12 12:57 UTC, JunAishima commented
also, please clean up the linting issues

2022-04-20 15:56 UTC, RobertSchaffer1 commented on nyxtools/flyer_eiger2.py
> +        x_mm = (kwargs["x_start_um"] / 1000, kwargs["x_end_um"] /1000)
Add back in the space after the / sign.

2022-04-28 21:43 UTC, JunAishima approved these changes
looks good

2022-05-05 17:24 UTC, merged